SELECT * FROM BATCH_LIST;

INSERT INTO BATCH_LIST(ID, BATCH_NAME, TOTAL_FIRE_COUNT, REMAINING_FIRE_COUNT, RUN_FOREVER, IS_CRON, REPEAT_INTERVAL_MS, INITIAL_OFFSET_MS, CRON_EXPR, CALLBACK_DATA)
SELECT 2, BATCH_NAME, 0, 0, RUN_FOREVER, true, 0, 1000,'5 * * * * ?', CALLBACK_DATA FROM BATCH_LIST;